"""Deterministic metric explanations. Formulas follow the tool code."""

from __future__ import annotations

from typing import Any

EXPLANATION_VERSION = "ui.metric.v1"

_NONE = "none"
_NO_DIR = "no_quality_direction"


def _item(
    metric_id: str,
    label_zh: str,
    value_kind: str,
    meaning: str,
    formula: str,
    limitations: list[str],
    *,
    unit_kind: str = "model_output",
) -> dict[str, Any]:
    return {
        "id": metric_id,
        "label_zh": label_zh,
        "value_kind": value_kind,
        "unit_kind": unit_kind,
        "meaning": meaning,
        "formula": formula,
        "direction": _NO_DIR,
        "threshold_kind": _NONE,
        "limitations": limitations,
        "explanation_version": EXPLANATION_VERSION,
    }


DEFINITIONS: dict[str, dict[str, Any]] = {
    "shape_tv": _item(
        "shape_tv",
        "时间点数 × 皮层顶点数",
        "object",
        "数组形状 [T, V]。T 是导出的时间点数，V 是表面顶点数。",
        "来自 validate_input 的 shape",
        ["不是体积图像的像素尺寸", "1 秒输出间隔不是扫描仪 TR"],
        unit_kind="count",
    ),
    "finite_ratio": _item(
        "finite_ratio",
        "有限值比例",
        "number",
        "有限数值占全部元素的比例。1 表示没有 NaN 或 Inf。",
        "count(isfinite(x)) / (T*V)",
        ["不是质量或准确率", "不评估脑响应真实性"],
        unit_kind="proportion",
    ),
    "valid_for_numeric_checks": _item(
        "valid_for_numeric_checks",
        "可用于数值检查",
        "boolean",
        "输入是否满足当前数值分析合同。",
        "validate_input.valid_for_numeric_checks",
        ["不是生理有效"],
        unit_kind="flag",
    ),
    "degenerate_signal": _item(
        "degenerate_signal",
        "退化或近常量",
        "boolean",
        "是否触发当前近常量判据。",
        "列标准差 <= abs_tol，或 <= rel_tol * max(|列均值|, 1e-12)",
        ["false 只表示没触发这条判据"],
        unit_kind="flag",
    ),
    "mean": _item("mean", "均值", "number", "全部元素的模型输出均值。", "mean(x)", ["负数不是错误", "不是 BOLD 百分比"]),
    "std": _item("std", "标准差", "number", "全部元素的标准差。", "std(x)", ["不是噪声估计"]),
    "min": _item("min", "最小值", "number", "全部元素的最小值。", "min(x)", ["不是统计下限"]),
    "max": _item("max", "最大值", "number", "全部元素的最大值。", "max(x)", ["不是统计上限"]),
    "quantiles": _item(
        "quantiles",
        "分位数",
        "object",
        "模型输出分布的分位数。",
        "quantile(x, q)",
        ["不是置信区间"],
    ),
    "satisfies_contrast_contract": _item(
        "satisfies_contrast_contract",
        "contrast 时序合同",
        "boolean",
        "这次时序结果是否使用了 contrast 信号。false 表示仍是 raw，不能当成 contrast 时序已经完成。",
        "stimulus_temporal_profile.satisfies_contrast_contract",
        ["false 不是样本损坏"],
        unit_kind="flag",
    ),
    "comparable": _item(
        "comparable",
        "灰屏可对照",
        "boolean",
        "图像预测与灰屏预测是否满足已实现的形状与配对条件。",
        "gray_control_contrast 的形状与配对检查",
        ["不是真实生理噪声估计"],
        unit_kind="flag",
    ),
    "overall_delta_rms": _item(
        "overall_delta_rms",
        "图像相对灰屏的整体差异",
        "number",
        "图像预测减去匹配灰屏后，全部元素的 RMS。等顶点权重。",
        "sqrt(mean((pred - gray)^2))",
        ["不是信噪比", "不是统计显著性", "不能单独证明真实脑响应"],
    ),
    "normalized_delta_over_control_rms": _item(
        "normalized_delta_over_control_rms",
        "差异相对灰屏 RMS",
        "number",
        "整体差异 RMS 除以灰屏预测自身的 RMS。分母接近 0 时为未定义。",
        "overall_delta_rms / sqrt(mean(gray^2))，分母 > 1e-12",
        ["不是激活提高的百分比"],
    ),
    "peak_frame": _item(
        "peak_frame",
        "RMS 峰值帧",
        "number",
        "contrast RMS 曲线最大值所在的帧序号。",
        "argmax(rms_t(pred - gray))",
        ["不是生理 HRF 峰"],
        unit_kind="index",
    ),
    "peak_time_s": _item(
        "peak_time_s",
        "RMS 峰值时间",
        "number",
        "峰值帧乘以采样间隔。只有时间对齐被标成 verified 时工具才填写。",
        "peak_frame * sampling_interval_s",
        ["不是通用异常时间"],
        unit_kind="seconds",
    ),
    "temporal_change_ratio": _item(
        "temporal_change_ratio",
        "空间均值的时间变化",
        "number",
        "全脑空间均值相邻变化的平均值，相对该均值序列的标准差。",
        "mean(|diff(spatial_mean)|) / (std(spatial_mean) + 1e-8)",
        ["没有覆盖每个顶点的局部变化"],
    ),
    "max_frame_diff_ratio": _item(
        "max_frame_diff_ratio",
        "空间均值的最大相邻变化比",
        "number",
        "空间均值相邻绝对变化的最大值，除以其中位数。分母加 1e-8。",
        "max(|diff(spatial_mean)|) / (median(|diff|) + 1e-8)",
        ["小分母会把比值抬高", "超过某个倍数不能自动判坏"],
    ),
    "max_step_over_median": _item(
        "max_step_over_median",
        "contrast RMS 的最大步长比",
        "number",
        "contrast 的相邻 RMS 变化（A）里，最大步长除以中位步长。它描述的是 RMS 曲线，不是全体顶点的模式变化 S。",
        "max(A) / median(A)；中位过小则记为不稳定",
        ["不能单独判定异常", "不是 S(t)"],
    ),
    "lag1_corr_mean": _item(
        "lag1_corr_mean",
        "相邻时间相关",
        "number",
        "各顶点相邻时间相关系数的平均值。短序列上不稳定的顶点不计入。",
        "mean(corr(x[v, t], x[v, t+1]))，未定义的顶点另计",
        ["越高不表示更健康"],
    ),
    "roi_contribution": _item(
        "roi_contribution",
        "ROI 贡献",
        "number",
        "声明的 transition 能量落在该 ROI 内的比例。",
        "sum(E in ROI) / sum(E over vertices)",
        ["不是激活概率", "不是统计显著性"],
        unit_kind="proportion",
    ),
    "embedding_available": _item(
        "embedding_available",
        "表征是否提取",
        "boolean",
        "CortexMAE 表征提取是否成功。",
        "cortex_mae.embedding_available",
        ["不是质量概率"],
        unit_kind="flag",
    ),
    "reference_score_assessed": _item(
        "reference_score_assessed",
        "是否做了参考评分",
        "boolean",
        "是否实际使用了兼容参考。没有参考不能显示成通过。",
        "cortex_mae.reference_score_assessed",
        ["无参考不等于通过"],
        unit_kind="flag",
    ),
    "evidence_confidence": _item(
        "evidence_confidence",
        "证据置信度",
        "number",
        "报告里的证据置信度。没有数值就是未提供，不能从工具次数推出来。",
        "report.evidence_confidence",
        ["未校准", "空值不是 0"],
        unit_kind="unknown",
    ),
    "recommended_training_weight": _item(
        "recommended_training_weight",
        "建议训练权重",
        "number",
        "报告里的训练权重。当前不自动赋值。",
        "report.recommended_training_weight",
        ["空值不是 0 或 1"],
        unit_kind="unknown",
    ),
    "lm_calls": _item(
        "lm_calls",
        "LLM 调用次数",
        "number",
        "账本里的 lm_calls。HTTP 成功次数不等于被接受的计划数。",
        "llm_usage.ledger.lm_calls",
        ["不要把它当成 accepted_plan_count"],
        unit_kind="count",
    ),
    "accepted_plan_count": _item(
        "accepted_plan_count",
        "接受的计划数",
        "number",
        "被接受的计划份数，和 HTTP 成功次数分开计。",
        "llm_usage.ledger.accepted_plan_count",
        ["一次 HTTP 成功不是一份新计划"],
        unit_kind="count",
    ),
    "input_tokens": _item(
        "input_tokens",
        "输入 token",
        "number",
        "提供方返回的输入 token。缺失就是未知。",
        "llm_usage.ledger.input_tokens",
        ["空值不计为 0"],
        unit_kind="count",
    ),
    "output_tokens": _item(
        "output_tokens",
        "输出 token",
        "number",
        "提供方返回的输出 token。缺失就是未知。",
        "llm_usage.ledger.output_tokens",
        ["空值不计为 0"],
        unit_kind="count",
    ),
    "api_usd": _item(
        "api_usd",
        "接口费用",
        "number",
        "账本里的美元费用。没有价格就显示未提供。",
        "llm_usage.ledger.api_usd",
        ["不能把空费用写成免费或 0 美元"],
        unit_kind="usd",
    ),
    "new_tribe_predictions": _item(
        "new_tribe_predictions",
        "新增 TRIBE 预测",
        "number",
        "这一轮新算出的预测数量。0 只表示没有新预测。",
        "generation.new_tribe_predictions",
        ["0 不一定等于缓存命中已经核对过"],
        unit_kind="count",
    ),
}


def definition(metric_id: str) -> dict[str, Any] | None:
    item = DEFINITIONS.get(metric_id)
    return dict(item) if item else None
